---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local

  vars:
    rg_name: "tpcloud-yn9"
    location: "norwayeast"

  tasks:
    - name: Create Resource Group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ rg_name }}"
        location: "{{ location }}"
